gomod:
  proxy: true

builds:
  - binary: ctlcheck
    main: ./
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X github.com/canstand/ctlcheck/app.AppVersion={{.Version}}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs'
    - '^test'

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/canstand/ctlcheck/compare/{{ .PreviousTag }}...{{ .Tag }}
